#!/bin/bash
# 🌶️ Complete Dataset Collection - All Commands
# Copy-paste commands for re-collecting entire dataset

echo "================================================================================"
echo "🌶️  COMPLETE DATASET COLLECTION - ALL COMMANDS"
echo "================================================================================"
echo ""
echo "This script contains ALL commands for collecting the complete dataset."
echo "You can copy-paste these commands one by one."
echo ""
echo "📊 Total: 192 images (16 peppers × 12 angles)"
echo "⏱️  Time: ~60-75 minutes"
echo ""
echo "================================================================================"
echo ""

# Session 1
echo "📍 SESSION 1: Red Large Peppers (8 peppers)"
echo "───────────────────────────────────────────────────────────────────────────────"
echo "Expected: 96 images (8 × 12 angles)"
echo "Time: ~32 minutes"
echo ""
echo "Command:"
echo "python3 collect_dataset.py --exposure 24 --gain 2 --output pepper_dataset/session1_red_large"
echo ""
echo "Press Enter when ready to see Session 2 commands..."
read

# Session 2
echo ""
echo "📍 SESSION 2: Red Defects (4 peppers)"
echo "───────────────────────────────────────────────────────────────────────────────"
echo "Expected: 48 images (4 × 12 angles)"
echo "Time: ~16 minutes"
echo ""
echo "Session 2.1: Red Rotten (พริกแดงเน่า)"
echo "python3 collect_dataset.py --exposure 24 --gain 2 --output pepper_dataset/session2_red_rotten"
echo ""
echo "Session 2.2: Red Insect (พริกแดงแมลงเจาะ)"
echo "python3 collect_dataset.py --exposure 24 --gain 2 --output pepper_dataset/session2_red_insect"
echo ""
echo "Session 2.3: Red Deformed (พริกแดงงอ)"
echo "python3 collect_dataset.py --exposure 24 --gain 2 --output pepper_dataset/session2_red_deformed"
echo ""
echo "Session 2.4: Red Wrinkled (พริกแดงเหี่ยว)"
echo "python3 collect_dataset.py --exposure 24 --gain 2 --output pepper_dataset/session2_red_wrinkled"
echo ""
echo "Press Enter when ready to see Session 3 commands..."
read

# Session 3
echo ""
echo "📍 SESSION 3: Green Varieties (4 peppers)"
echo "───────────────────────────────────────────────────────────────────────────────"
echo "Expected: 48 images (4 × 12 angles)"
echo "Time: ~16 minutes"
echo ""
echo "Session 3.1: Green Medium (เขียวขนาดกลาง)"
echo "python3 collect_dataset.py --exposure 24 --gain 2 --output pepper_dataset/session3_green_medium"
echo ""
echo "Session 3.2: Green Small (เขียวขนาดเล็ก)"
echo "python3 collect_dataset.py --exposure 24 --gain 2 --output pepper_dataset/session3_green_small"
echo ""
echo "Session 3.3: Green Tiny (เขียวขนาดเล็กมาก)"
echo "python3 collect_dataset.py --exposure 24 --gain 2 --output pepper_dataset/session3_green_tiny"
echo ""
echo "Session 3.4: Green Rotten (เขียวเน่า)"
echo "python3 collect_dataset.py --exposure 24 --gain 2 --output pepper_dataset/session3_green_rotten"
echo ""
echo "Press Enter when ready to see verification commands..."
read

# Verification
echo ""
echo "✅ VERIFICATION COMMANDS"
echo "───────────────────────────────────────────────────────────────────────────────"
echo ""
echo "Count all images:"
echo "find pepper_dataset -name '*.jpg' | wc -l"
echo ""
echo "Count per session:"
echo "for dir in pepper_dataset/session*_*; do echo \"\$(basename \$dir): \$(find \$dir -name '*.jpg' | wc -l) images\"; done"
echo ""
echo "Summary:"
echo "echo '=== Dataset Summary ==='"
echo "echo 'Session 1: \$(find pepper_dataset/session1_* -name \"*.jpg\" | wc -l) images'"
echo "echo 'Session 2: \$(find pepper_dataset/session2_* -name \"*.jpg\" | wc -l) images'"
echo "echo 'Session 3: \$(find pepper_dataset/session3_* -name \"*.jpg\" | wc -l) images'"
echo "echo 'Total: \$(find pepper_dataset -name \"*.jpg\" | wc -l) images'"
echo ""
echo "================================================================================"
echo "✅ ALL COMMANDS DISPLAYED!"
echo "================================================================================"
echo ""
echo "📝 Workflow per pepper:"
echo "   1. Place pepper → remove hand"
echo "   2. Wait 3-5 seconds"
echo "   3. Press SPACE → countdown → capture"
echo "   4. Rotate ~30° → repeat 12 times"
echo ""
echo "💡 Tips:"
echo "   - Texture should be visible (sharp)"
echo "   - Remove hand quickly after placing"
echo "   - Don't move during countdown"
echo ""
echo "🎯 Expected result: 192 images total"
echo ""
echo "================================================================================"
