name: Claude Code Background Task

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-respond:
    # รันเมื่อมีการแท็ก @claude ใน comment
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          prompt: |
            ผู้ใช้แท็ก @claude ใน comment นี้:
            "${{ github.event.comment.body }}"

            กรุณาตอบคำถามหรือทำตามที่ผู้ใช้ขอ
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
