name: Test Secret

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test ANTHROPIC_API_KEY
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          if [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "❌ ANTHROPIC_API_KEY is empty or not set"
            exit 1
          else
            echo "✅ ANTHROPIC_API_KEY is set"
            echo "Length: ${#ANTHROPIC_API_KEY} characters"
            echo "First 20 chars: ${ANTHROPIC_API_KEY:0:20}..."
          fi
